---
title: "Word frequency ordination"
author: "Kali Mattingly"
date: "March 31, 2019"
output: html_document
---


Data and packages
```{r}
dir <- paste(getwd(),"/mattinglyetal_data.csv",sep="")
madataes2 <- read.csv(dir)

dat <- madataes2[,c(1:3,5:6,8:13)] # isolate columns of word frequencies that will be included in ordination
datu <- unique(dat) # cut out duplicated rows (rows are duplicated due to multiple effect sizes per paper)
rownames(datu) <- datu[,1] # make refname rownames
ft <- datu[,c(2:11)]
ft2 <- ft[c(1:51,53:111,113:118,120:130,132:136,138:142,144:164,166:179,181:202),] # remove papers where words do not appear (because ordination cannot handle all-zero observations for a row): trometer (180), shurin (165), pace (143), nalepa (137), meyerson (131), lozano (119), leroy (112), driver (52)

require(vegan)
```


NMDS ordination
```{r}
ft2ord <- metaMDS(ft2, trymax=300, transformation=FALSE) #stress=0.193

# plot
fig <- plot(ft2ord, type="none")
points(fig, "sites", col="black", cex=0.75, pch=20)
points(fig, "species", col="red", cex=2, pch=8)
text(fig, "species", col="black", cex=1)

ft2scores <- as.data.frame(scores(ft2ord, "sites")) # these are the nmds scores analyzed for random forest. The scores from the original run are written as columns in `mattinglyetal_data.csv`
```


PERMANOVA example
```{r}
dir <- paste(getwd(),"/mattinglyetal_data_permanova.csv",sep="")
datenv2 <- read.csv(dir) #this file is abbreviated version of `mattinglyetal_data.csv` that has one row for each paper (so cannot have multiple species or effect sizes per paper, etc.). Also must not have the rows for the 8 papers w/ 0 words.
ft2dist <- vegdist(ft2) # distance matrix for dispersion test

# trophic level of invader
adonis(ft2~trophic_invader, datenv2, permutations=9999) # permanova 
anova(betadisper(ft2dist, group=datenv2$trophic_invader)) # dispersion test
```
